name: Publishing crates on cargo

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  cargo:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: ./compare_versions.sh
        name: Compare version
      - run: cargo publish -p obrewin-utils
        name: Publish utils
      - run: cargo publish -p obrewin-data-structures
        name: Publish data structures
      - run: cargo publish -p obrewin-network
        name: Publish networking components
